"""Constantes du protocole, reprises de protocole/constantes.yaml."""

VERSION = "0.1"

ETIQUETTE_ATTEST = b"PRESENCE/v0.1/ATTEST"
ETIQUETTE_TEMOIN = b"PRESENCE/v0.1/TEMOIN"
ETIQUETTE_REQUETE = "PRESENCE/v0.1/REQ"

PERIODE_NONCE_S = 45
DUREE_FENETRE_MS = 300_000
RESTE_MIN_FENETRE_MS = 120_000
SEUIL_PRESENT = 0.8
FENETRES_RETARD = 3
ECART_DOUBLE_PRESENCE_MS = 120_000
DELAI_PRESENCE_ENSEIGNANT_MS = 180_000
TOLERANCE_HORLOGE_MS = 120_000
EQUIPEMENT_EN_LIGNE_MS = 90_000

STATUTS = ("PRESENT", "RETARD", "DEPART_ANTICIPE", "PARTIEL", "A_VERIFIER", "ABSENT")
ROLES = ("ETUDIANT", "ENSEIGNANT", "SCOLARITE", "ADMIN", "AUDITEUR")
ROLES_PERSONNEL = ("SCOLARITE", "ADMIN", "AUDITEUR")
